import AppKit

/// สำรอง/คืนค่าคลิปบอร์ดของผู้ใช้ได้ครบทุกรูปแบบ (ข้อความ, RTF, รูปภาพ, ไฟล์ ฯลฯ) ตามลำดับเดิม
enum Clipboard {
    typealias Snapshot = [[(NSPasteboard.PasteboardType, Data)]]

    // โปรแกรมจัดการคลิปบอร์ด (Maccy, Raycast, Alfred, Paste ฯลฯ) จะไม่บันทึกรายการที่มีรูปแบบเหล่านี้
    // ดู http://nspasteboard.org
    private static let transientTypes = [
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
    ]

    private static var pasteboard: NSPasteboard {
        return NSPasteboard.general
    }

    static var changeCount: Int {
        return pasteboard.changeCount
    }

    static func capture() -> Snapshot {
        return (pasteboard.pasteboardItems ?? []).map { item in
            item.types.compactMap { type in item.data(forType: type).map { (type, $0) } }
        }
    }

    /// คืนค่าคลิปบอร์ดจากสำเนา (ไม่ให้ไปซ้ำในโปรแกรมจัดการคลิปบอร์ด)
    static func restore(_ snapshot: Snapshot?) {
        guard let snapshot = snapshot else { return }
        pasteboard.clearContents()
        let items = snapshot.map { entries -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for (type, data) in entries { item.setData(data, forType: type) }
            return item
        }
        if let first = items.first { markTransient(first) }
        if !items.isEmpty { pasteboard.writeObjects(items) }
    }

    static func text() -> String? {
        return pasteboard.string(forType: .string)
    }

    /// ใส่ข้อความลงคลิปบอร์ด โดยไม่ให้โปรแกรมจัดการคลิปบอร์ดบันทึกไว้
    static func setText(_ text: String) -> Bool {
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        markTransient(item)
        return pasteboard.writeObjects([item])
    }

    // VS Code (และโปรแกรมที่สร้างจาก Electron) เก็บ metadata เป็น JSON ไว้ในรูปแบบเหล่านี้
    private static let editorMetadataTypes = [
        NSPasteboard.PasteboardType("org.chromium.web-custom-data"),
        NSPasteboard.PasteboardType("vscode-editor-data"),
    ]

    private static let emptySelectionMarker = "\"isFromEmptySelection\":true"

    /// โปรแกรมแก้โค้ดบางตัว (VS Code) จะคัดลอกทั้งบรรทัดเมื่อกด Cmd+C โดยไม่ได้คลุมข้อความ
    /// ถ้าเป็นกรณีนี้ต้องไม่แปลง ไม่อย่างนั้นจะได้บรรทัดซ้ำเพิ่มเข้ามา
    static func isWholeLineCopy() -> Bool {
        for type in editorMetadataTypes {
            guard let data = pasteboard.data(forType: type) else { continue }
            // ข้อมูลของ Chromium เป็นไบนารีที่มีข้อความ UTF-16 อยู่ข้างใน จึงค้นหาเป็นไบต์แทนการแปลงทั้งก้อนเป็นข้อความ
            for encoding in [String.Encoding.utf8, .utf16LittleEndian] {
                if let marker = emptySelectionMarker.data(using: encoding), data.range(of: marker) != nil {
                    return true
                }
            }
        }
        return false
    }

    private static func markTransient(_ item: NSPasteboardItem) {
        for type in transientTypes { item.setData(Data(), forType: type) }
    }
}
